
        <footer>
            <p><strong>2025 SpeedX</strong> - "Bridging innovation and the infinite."</p>
            
            <div>
                <p><strong>SpeedX</strong></p>
                <img src="images/speedx_logo.png" height="80" width="80" alt="speedX logo">
            </div>
            
            <div id="contact-info">
                <a href="mailto:info@speedx.com.au"><strong>Contact us:</strong> info@speedx.com.au</a>
                <p><strong>Address:</strong> 42 Galaxy Road, Orbit City</p>
                <p><strong>Phone:</strong> +1-800-555-SpeedX</p>
                <a href="https://trinhthaianhtuan.atlassian.net/jira/software/projects/HCFPP1/boards/35/timeline?" target="_blank">
                    <strong>Visit our Jira project</strong>
                </a>
                
                <a href="https://github.com/bibibilatoi/project1" target="_blank">
                    <strong>Visit the GitHub repo of this project</strong>
                </a>
                <p>&copy; 2025 SpeedX. All rights reserved.</p>
            </div>
        </footer>
</body>
</html>