
<footer>
    <strong>2025 SpeedX - "Bridging innovation and the infinite."</strong>
    
    <div id="footer-logo">
        <p><strong>SpeedX</strong></p>
        <img src="images/speedx_logo.png" height="80" width="80" alt="speedX logo">
    </div>
    
    <div id="contact-info">
        <p><strong>Address:</strong> 42 Galaxy Road, Orbit City</p>
        <a href="mailto:info@speedx.com.au"><strong>Contact us:</strong> info@speedx.com.au</a>
        <p><strong>Phone:</strong> +1-800-555-SpeedX</p>
    </div>
    <div id="project-info">
        <a href="https://github.com/users/bibibilatoi/projects/2" target="_blank">
            Visit our Github project
        </a>
        
        <a href="https://github.com/bibibilatoi/project2" target="_blank">
            Visit the GitHub repo of this project
        </a>
        <strong>&copy; 2025 SpeedX. All rights reserved.</strong>
    </div>
</footer>
