  <nav id="nav-menu">
            <input type="checkbox" id="nav-menu-toggle">
            <label for="nav-menu-toggle">Menu</label>
            <ul>
                <li><a id="current-page" href="#">Home Page</a></li>
                <li><a href="jobs.html">Jobs Positions</a></li>
                <li><a href="apply.html">Applications</a></li>
                <li><a href="about.html">About Us</a></li>
                <li><a href="mailto:info@speedx.com.au"><strong>Contact us:</strong> info@speedx.com.au</a></li>
            </ul>
    </nav>